# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
