# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180306_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
